import { Action, Clipboard, Icon, Toast, environment, showInFinder, showToast } from "@raycast/api";
import { randomUUID } from "node:crypto";
import { mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { useRef } from "react";
import { escapeXml } from "./charts";
import { savePng, SvgImage } from "./png";

export type ExportCard = {
  title: string;
  subtitle: string;
  generatedAt: string;
  stats: { label: string; value: string }[];
  chart?: SvgImage;
  rows?: { name: string; value: string }[];
  note: string;
};

export function reportCard(card: ExportCard): SvgImage {
  const dark = environment.appearance === "dark";
  const background = dark ? "#191a1c" : "#ffffff";
  const surface = dark ? "#242629" : "#f3f5f7";
  const text = dark ? "#f5f5f6" : "#202124";
  const muted = dark ? "#a9adb5" : "#626975";
  const border = dark ? "#363a40" : "#e1e5eb";
  const accent = dark ? "#449dff" : "#0a7ff5";
  const width = 656;
  const parts: string[] = [];
  const label = (x: number, y: number, value: string, size = 13, color = text, weight = 400) =>
    `<text x="${x}" y="${y}" fill="${color}" font-size="${size}" font-weight="${weight}">${escapeXml(value)}</text>`;
  parts.push(label(48, 48, "CODEX REPORT", 11, accent, 700));
  parts.push(label(48, 88, card.title, 28, text, 700));
  parts.push(label(48, 115, card.subtitle, 13, muted));
  let y = 141;
  card.stats.forEach((stat, index) => {
    const x = 48 + (index % 2) * 286;
    const top = y + Math.floor(index / 2) * 77;
    parts.push(`<rect x="${x}" y="${top}" width="274" height="65" rx="10" fill="${surface}"/>`);
    parts.push(label(x + 14, top + 21, stat.label, 11, muted));
    parts.push(label(x + 14, top + 47, stat.value, 21, text, 600));
  });
  y += Math.ceil(card.stats.length / 2) * 77 + 24;
  if (card.chart) {
    parts.push(`<g transform="translate(48,${y})">${card.chart.body}</g>`);
    y += card.chart.height + 20;
  }
  for (const row of card.rows ?? []) {
    // Wrap long names instead of losing repository or model identity in exports.
    const lines = Array.from(row.name).join("").match(/.{1,42}/gu) ?? [""];
    for (const [index, line] of lines.entries()) parts.push(label(48, y + index * 19, line));
    parts.push(`<text x="608" y="${y}" text-anchor="end" fill="${text}" font-size="13" font-weight="600">${escapeXml(row.value)}</text>`);
    y += lines.length * 19 + 17;
    parts.push(`<path d="M48 ${y - 9} H608" stroke="${border}"/>`);
  }
  for (const line of card.note.match(/.{1,78}(?:\s|$)|\S{1,78}/g) ?? []) {
    parts.push(label(48, y + 12, line.trim(), 11, muted));
    y += 17;
  }
  y += 26;
  parts.push(`<path d="M48 ${y} H608" stroke="${border}"/>`);
  parts.push(label(48, y + 26, "Generated by codex-report", 12, text, 600));
  parts.push(label(48, y + 46, "https://github.com/flkrnr/codex-report", 12, accent));
  parts.push(label(48, y + 69, `Data updated ${new Date(card.generatedAt).toLocaleString("en-US")}`, 10, muted));
  const height = Math.ceil(y + 94);
  return {
    width,
    height,
    body: `<g font-family="-apple-system,Helvetica,sans-serif"><rect width="${width}" height="${height}" rx="18" fill="${background}"/><rect x="0.5" y="0.5" width="${width - 1}" height="${height - 1}" rx="18" fill="none" stroke="${border}"/>${parts.join("")}</g>`,
  };
}

export function ExportPngAction({ card }: { card: ExportCard }) {
  const running = useRef(false);
  async function exportImage() {
    if (running.current) return;
    running.current = true;
    let saved: string | undefined;
    const toast = await showToast({ style: Toast.Style.Animated, title: "Exporting PNG…" });
    try {
      const downloads = join(homedir(), "Downloads");
      await mkdir(downloads, { recursive: true });
      const destination = join(downloads, `codex-report-${new Date().toISOString().replace(/[:.]/g, "-")}-${randomUUID().slice(0, 8)}.png`);
      await savePng(reportCard(card), destination);
      saved = destination;
      toast.primaryAction = { title: "Show in Finder", onAction: () => showInFinder(destination) };
      await Clipboard.copy({ file: destination });
      toast.style = Toast.Style.Success;
      toast.title = "PNG Saved and Copied";
      toast.message = "Saved to Downloads. Ready to paste.";
    } catch (reason) {
      toast.style = Toast.Style.Failure;
      toast.title = saved ? "PNG Saved; Clipboard Copy Failed" : "Could Not Export PNG";
      toast.message = reason instanceof Error ? reason.message : String(reason);
    } finally {
      running.current = false;
    }
  }
  return <Action title="Export as PNG" icon={Icon.Download} shortcut={{ modifiers: ["cmd", "shift"], key: "e" }} onAction={exportImage} />;
}
